import type { ThemeTokens } from './tokens';

export interface ThemePreset {
  id: string;
  name: string;
  emoji: string;
  blurb: string;
  tokens: ThemeTokens;
}

// Shared defaults so each preset only specifies what differs.
const base: ThemeTokens = {
  scheme: 'light',
  accent: '#3a6fa8',
  accent2: '#22b8cf',
  bg: '#eef2f8',
  bg2: '#e3ebf6',
  surface: '#ffffff',
  surface2: '#eef2f9',
  border: '#e3e6ee',
  text: '#1c1e26',
  textMuted: '#5b6171',
  heading: '#16263c',
  sidebarBg: '#1b2a4a',
  sidebarBg2: '#0f1b33',
  sidebarText: '#cbd6ec',
  sidebarActiveBg: '#3a6fa8',
  sidebarActiveText: '#ffffff',
  radius: 16,
  gap: 16,
  borderWidth: 1,
  density: 'comfortable',
  fontFamily: 'System',
  headingFamily: 'System',
  fontScale: 1,
  background: 'none',
  patternColor: 'rgba(0,0,0,0.05)',
  cardStyle: 'elevated',
  sidebarStyle: 'pills',
  sidebarGradient: true,
  glow: false,
  animations: true,
  cardImageTint: false,
};

const t = (over: Partial<ThemeTokens>): ThemeTokens => ({ ...base, ...over });

export const THEMES: ThemePreset[] = [
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '🌌',
    blurb: 'Glassy dark, glowing indigo, gradient sidebar. The showpiece.',
    tokens: t({
      scheme: 'dark',
      accent: '#7c6dff',
      accent2: '#22d3ee',
      bg: '#0c0e16',
      bg2: '#141a2e',
      surface: '#171a26',
      surface2: '#1e2333',
      border: '#2a3047',
      text: '#e9ebf5',
      textMuted: '#9aa1bd',
      heading: '#c7c2ff',
      sidebarBg: '#1a1640',
      sidebarBg2: '#0c0e1e',
      sidebarText: '#c4c8e4',
      sidebarActiveBg: '#7c6dff',
      sidebarActiveText: '#ffffff',
      patternColor: 'rgba(124,109,255,0.07)',
      background: 'grid',
      cardStyle: 'glass',
      glow: true,
      cardImageTint: true,
    }),
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    emoji: '📐',
    blurb: 'Graph-paper drafting board. GT navy + gold, crisp and scholarly.',
    tokens: t({
      accent: '#B3A369',
      accent2: '#003057',
      bg: '#e7eef7',
      bg2: '#dde7f3',
      surface: '#ffffff',
      surface2: '#eaf0f8',
      border: '#bcccE3',
      text: '#10243d',
      textMuted: '#43566f',
      heading: '#003057',
      sidebarBg: '#003057',
      sidebarBg2: '#001e38',
      sidebarText: '#cdd8ea',
      sidebarActiveBg: '#B3A369',
      sidebarActiveText: '#10243d',
      background: 'grid',
      patternColor: 'rgba(0,48,87,0.12)',
      headingFamily: 'Mono',
      cardStyle: 'outlined',
      borderWidth: 2,
    }),
  },
  {
    id: 'aurora',
    name: 'Aurora',
    emoji: '🪻',
    blurb: 'Violet→teal gradients, soft glow, glassy gradient-border cards.',
    tokens: t({
      scheme: 'dark',
      accent: '#a855f7',
      accent2: '#2dd4bf',
      bg: '#0f1020',
      bg2: '#1a1136',
      surface: '#191a2e',
      surface2: '#22203b',
      border: '#322a52',
      text: '#ecebfb',
      textMuted: '#a39ec9',
      heading: '#d8b4fe',
      sidebarBg: '#2a1457',
      sidebarBg2: '#0c1230',
      sidebarText: '#d6cdf2',
      sidebarActiveBg: '#a855f7',
      sidebarActiveText: '#ffffff',
      background: 'gradient',
      cardStyle: 'gradient-border',
      glow: true,
      cardImageTint: true,
    }),
  },
  {
    id: 'notebook',
    name: 'Notebook',
    emoji: '📓',
    blurb: 'Real ruled paper, red margin line, cozy serif.',
    tokens: t({
      accent: '#c0392b',
      accent2: '#2e7d32',
      bg: '#faf6ea',
      bg2: '#f4eedb',
      surface: '#fffdf6',
      surface2: '#f3ecd8',
      border: '#e2d6b8',
      text: '#3a3326',
      textMuted: '#7a6f57',
      heading: '#7a3b32',
      sidebarBg: '#42382a',
      sidebarBg2: '#2e2619',
      sidebarText: '#ece1c8',
      sidebarActiveBg: '#c0392b',
      sidebarActiveText: '#fffdf6',
      background: 'paper',
      patternColor: 'rgba(80,110,170,0.18)',
      headingFamily: 'Serif',
      fontFamily: 'Serif',
      cardStyle: 'outlined',
      sidebarGradient: false,
    }),
  },
  {
    id: 'gt-buzz',
    name: 'GT Buzz',
    emoji: '🐝',
    blurb: 'Full Georgia Tech spirit — navy, Tech gold, white.',
    tokens: t({
      accent: '#B3A369',
      accent2: '#EAAA00',
      bg: '#eef1f6',
      bg2: '#e4e9f2',
      surface: '#ffffff',
      surface2: '#e9edf4',
      border: '#d0d8e6',
      text: '#003057',
      textMuted: '#4a5b73',
      heading: '#003057',
      sidebarBg: '#003057',
      sidebarBg2: '#002340',
      sidebarText: '#d6c99b',
      sidebarActiveBg: '#EAAA00',
      sidebarActiveText: '#003057',
      glow: true,
    }),
  },
  {
    id: 'luminae-blue',
    name: 'Luminae Blue',
    emoji: '🔵',
    blurb: 'Clean navy + cyan — matches the Luminae apps.',
    tokens: t({}),
  },
  {
    id: 'sky',
    name: 'Sky',
    emoji: '🌤️',
    blurb: 'Airy blue gradient, big rounded glassy cards.',
    tokens: t({
      accent: '#2f80ed',
      accent2: '#56ccf2',
      bg: '#e6f0fb',
      bg2: '#d3e6fb',
      surface: '#ffffff',
      surface2: '#dbeafe',
      border: '#c2dcf6',
      text: '#0f2740',
      textMuted: '#4f6b8a',
      heading: '#1b4f8a',
      sidebarBg: '#1d3a8a',
      sidebarBg2: '#0f2563',
      sidebarText: '#d3e2fb',
      sidebarActiveBg: '#2f80ed',
      sidebarActiveText: '#ffffff',
      background: 'gradient',
      radius: 22,
      cardStyle: 'glass',
      glow: true,
    }),
  },
  {
    id: 'oled',
    name: 'OLED Black',
    emoji: '⬛',
    blurb: 'True black, neon indigo glow, battery-friendly.',
    tokens: t({
      scheme: 'dark',
      accent: '#7c6dff',
      accent2: '#22d3ee',
      bg: '#000000',
      bg2: '#070709',
      surface: '#0c0d12',
      surface2: '#14151c',
      border: '#23252e',
      text: '#e7e9ef',
      textMuted: '#8b909c',
      heading: '#b9b2ff',
      sidebarBg: '#050507',
      sidebarBg2: '#000000',
      sidebarText: '#c4c8d4',
      sidebarActiveBg: '#7c6dff',
      sidebarActiveText: '#ffffff',
      cardStyle: 'gradient-border',
      glow: true,
      sidebarGradient: false,
    }),
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '🌲',
    blurb: 'Calm pine greens, warm and grounded.',
    tokens: t({
      accent: '#2e7d57',
      accent2: '#9ccc65',
      bg: '#eaf3ec',
      bg2: '#dfeee2',
      surface: '#ffffff',
      surface2: '#e2ede5',
      border: '#cce0d2',
      text: '#16331f',
      textMuted: '#4f6b58',
      heading: '#1f5b3c',
      sidebarBg: '#173a2a',
      sidebarBg2: '#0d281c',
      sidebarText: '#cfe6d6',
      sidebarActiveBg: '#2e7d57',
      sidebarActiveText: '#ffffff',
      glow: true,
    }),
  },
  {
    id: 'sunset',
    name: 'Sunset',
    emoji: '🌅',
    blurb: 'Warm coral→amber gradient, soft glow.',
    tokens: t({
      accent: '#ef6c4d',
      accent2: '#f6b73c',
      bg: '#fdeee6',
      bg2: '#fbdfd0',
      surface: '#ffffff',
      surface2: '#fbe2d6',
      border: '#f3cdbd',
      text: '#3d2218',
      textMuted: '#7c5749',
      heading: '#b54328',
      sidebarBg: '#5a2a23',
      sidebarBg2: '#3a1813',
      sidebarText: '#f6d8cb',
      sidebarActiveBg: '#ef6c4d',
      sidebarActiveText: '#ffffff',
      background: 'gradient',
      cardStyle: 'glass',
      glow: true,
    }),
  },
  {
    id: 'mono',
    name: 'Mono',
    emoji: '⬜',
    blurb: 'Minimal grayscale, one quiet accent, flat.',
    tokens: t({
      accent: '#18181b',
      accent2: '#6b7280',
      bg: '#f4f4f5',
      bg2: '#ececee',
      surface: '#ffffff',
      surface2: '#ececee',
      border: '#dcdce0',
      text: '#18181b',
      textMuted: '#71717a',
      heading: '#000000',
      sidebarBg: '#18181b',
      sidebarBg2: '#000000',
      sidebarText: '#d4d4d8',
      sidebarActiveBg: '#3f3f46',
      sidebarActiveText: '#ffffff',
      cardStyle: 'flat',
      radius: 10,
      sidebarGradient: false,
      animations: false,
    }),
  },
];

export const DEFAULT_THEME_ID = 'midnight';

export function getTheme(id: string): ThemePreset {
  return THEMES.find((p) => p.id === id) ?? THEMES[0];
}
