import type { ThemeTokens } from './tokens';

export interface ThemePreset {
  id: string;
  name: string;
  emoji: string;
  blurb: string;
  tokens: ThemeTokens;
}

// Shared defaults so each preset only specifies what differs.
const base: ThemeTokens = {
  scheme: 'light',
  accent: '#3a6fa8',
  accent2: '#22b8cf',
  bg: '#f5f7fb',
  surface: '#ffffff',
  surface2: '#eef2f9',
  border: '#e3e6ee',
  text: '#1c1e26',
  textMuted: '#5b6171',
  sidebarBg: '#1b2a4a',
  sidebarText: '#cbd6ec',
  sidebarActiveBg: '#3a6fa8',
  sidebarActiveText: '#ffffff',
  radius: 14,
  gap: 16,
  density: 'comfortable',
  fontFamily: 'System',
  headingFamily: 'System',
  fontScale: 1,
  background: 'none',
  patternColor: 'rgba(0,0,0,0.05)',
  cardStyle: 'elevated',
  sidebarStyle: 'pills',
};

const t = (over: Partial<ThemeTokens>): ThemeTokens => ({ ...base, ...over });

export const THEMES: ThemePreset[] = [
  {
    id: 'blueprint',
    name: 'Blueprint',
    emoji: '📐',
    blurb: 'Graph-paper background, GT navy + gold. Schoolish and crisp.',
    tokens: t({
      accent: '#B3A369', // GT gold
      accent2: '#003057', // GT navy
      bg: '#eef2f8',
      surface: '#ffffff',
      surface2: '#e7edf6',
      border: '#cdd8ea',
      text: '#10243d',
      textMuted: '#4a5b73',
      sidebarBg: '#003057',
      sidebarText: '#cdd8ea',
      sidebarActiveBg: '#B3A369',
      sidebarActiveText: '#10243d',
      background: 'grid',
      patternColor: 'rgba(0,48,87,0.08)',
      headingFamily: 'Mono',
      cardStyle: 'outlined',
    }),
  },
  {
    id: 'luminae-blue',
    name: 'Luminae Blue',
    emoji: '🔵',
    blurb: 'Navy sidebar, clean white, blue/cyan accents — matches your apps.',
    tokens: t({}),
  },
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '🌙',
    blurb: 'Dark, electric indigo accent. The Nova default.',
    tokens: t({
      scheme: 'dark',
      accent: '#6d5efc',
      accent2: '#22d3ee',
      bg: '#14161c',
      surface: '#1f222a',
      surface2: '#272b35',
      border: '#2c2f38',
      text: '#e7e9ef',
      textMuted: '#9aa0ad',
      sidebarBg: '#16181d',
      sidebarText: '#c4c8d4',
      sidebarActiveBg: '#6d5efc',
      sidebarActiveText: '#ffffff',
      patternColor: 'rgba(255,255,255,0.04)',
      cardStyle: 'glass',
    }),
  },
  {
    id: 'oled',
    name: 'OLED Black',
    emoji: '⬛',
    blurb: 'True black for battery + contrast, indigo accent.',
    tokens: t({
      scheme: 'dark',
      accent: '#7c6dff',
      accent2: '#22d3ee',
      bg: '#000000',
      surface: '#0c0d10',
      surface2: '#141519',
      border: '#23252c',
      text: '#e7e9ef',
      textMuted: '#8b909c',
      sidebarBg: '#000000',
      sidebarText: '#c4c8d4',
      sidebarActiveBg: '#7c6dff',
      sidebarActiveText: '#ffffff',
    }),
  },
  {
    id: 'sky',
    name: 'Sky',
    emoji: '☁️',
    blurb: 'Airy light-blue gradient, soft rounded cards.',
    tokens: t({
      accent: '#2f80ed',
      accent2: '#56ccf2',
      bg: '#e8f1fb',
      surface: '#ffffff',
      surface2: '#dbeafe',
      border: '#c7ddf5',
      text: '#0f2740',
      textMuted: '#4f6b8a',
      sidebarBg: '#1d3a8a',
      sidebarText: '#d3e2fb',
      sidebarActiveBg: '#2f80ed',
      sidebarActiveText: '#ffffff',
      background: 'gradient',
      patternColor: 'rgba(47,128,237,0.12)',
      radius: 18,
    }),
  },
  {
    id: 'notebook',
    name: 'Notebook',
    emoji: '📓',
    blurb: 'Cream paper, ruled lines, cozy serif headings.',
    tokens: t({
      accent: '#c0392b',
      accent2: '#2e7d32',
      bg: '#faf6ec',
      surface: '#fffdf7',
      surface2: '#f3ecda',
      border: '#e3d8be',
      text: '#3a3326',
      textMuted: '#7a6f57',
      sidebarBg: '#3a3326',
      sidebarText: '#e8dec7',
      sidebarActiveBg: '#c0392b',
      sidebarActiveText: '#fffdf7',
      background: 'ruled',
      patternColor: 'rgba(58,51,38,0.10)',
      headingFamily: 'Serif',
      cardStyle: 'outlined',
    }),
  },
  {
    id: 'gt-buzz',
    name: 'GT Buzz',
    emoji: '🐝',
    blurb: 'Full Georgia Tech spirit — navy, gold, white.',
    tokens: t({
      accent: '#B3A369',
      accent2: '#EAAA00',
      bg: '#f2f4f8',
      surface: '#ffffff',
      surface2: '#e9edf4',
      border: '#d4dae6',
      text: '#003057',
      textMuted: '#54657c',
      sidebarBg: '#003057',
      sidebarText: '#d6c99b',
      sidebarActiveBg: '#B3A369',
      sidebarActiveText: '#003057',
      cardStyle: 'elevated',
    }),
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '🌲',
    blurb: 'Calm greens, easy on the eyes.',
    tokens: t({
      accent: '#2e7d57',
      accent2: '#7cb342',
      bg: '#eef4ef',
      surface: '#ffffff',
      surface2: '#e2ede5',
      border: '#cfe0d4',
      text: '#17331f',
      textMuted: '#4f6b58',
      sidebarBg: '#1b3a2b',
      sidebarText: '#cfe6d6',
      sidebarActiveBg: '#2e7d57',
      sidebarActiveText: '#ffffff',
    }),
  },
  {
    id: 'sunset',
    name: 'Sunset',
    emoji: '🌅',
    blurb: 'Warm coral + amber, gentle gradient.',
    tokens: t({
      accent: '#ef6c4d',
      accent2: '#f6b73c',
      bg: '#fdf0ea',
      surface: '#ffffff',
      surface2: '#fbe2d6',
      border: '#f3cdbd',
      text: '#3d2218',
      textMuted: '#7c5749',
      sidebarBg: '#5a2a23',
      sidebarText: '#f6d8cb',
      sidebarActiveBg: '#ef6c4d',
      sidebarActiveText: '#ffffff',
      background: 'gradient',
      patternColor: 'rgba(239,108,77,0.12)',
    }),
  },
  {
    id: 'mono',
    name: 'Mono',
    emoji: '⬜',
    blurb: 'Minimal grayscale + a single accent.',
    tokens: t({
      accent: '#111827',
      accent2: '#6b7280',
      bg: '#f4f4f5',
      surface: '#ffffff',
      surface2: '#ececee',
      border: '#dcdce0',
      text: '#18181b',
      textMuted: '#71717a',
      sidebarBg: '#18181b',
      sidebarText: '#d4d4d8',
      sidebarActiveBg: '#3f3f46',
      sidebarActiveText: '#ffffff',
      cardStyle: 'flat',
      radius: 10,
    }),
  },
];

export const DEFAULT_THEME_ID = 'blueprint';

export function getTheme(id: string): ThemePreset {
  return THEMES.find((p) => p.id === id) ?? THEMES[0];
}
